<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>0658a176-6c1e-49b4-9eb4-be75062d56f2</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\backend\NoNeed2Ask.Api.csproj" />
    </ItemGroup>

</Project>
